command = "hugo --gc -s . --minify"

[context.production.environment]
  HUGO_VERSION = "0.69.2"
  GO_VERSION="1.12"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.69.2"
  GO_VERSION="1.12"
  

[context.branch-deploy]
command = "hugo --gc -b $DEPLOY_PRIME_URL"

[context.deploy-preview]
command = "hugo --gc -b $DEPLOY_PRIME_URL"
